---
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "Testing"
    - debug:
        msg: "Testing_ONE"
      tags:
        - one
    - debug:
        msg: "Testing_TWO"
      tags:
        - two